# Generated by Django 4.2 on 2023-04-29 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=100)),
                ('Category', models.CharField(max_length=100)),
                ('Recipe', models.CharField(max_length=500)),
            ],
            options={
                'ordering': ('Title',),
            },
        ),
    ]
